server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: smart-meeting-room

  datasource:
    url: jdbc:mysql://mysql-98ade40-patiltejasree02-e0b.l.aivencloud.com:10960/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_3QrrNtikjN6JbIDfCx4
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: smartmeetinghub@gmail.com
    password: amlxwcaqedoqmsha

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  secret: ${JWT_SECRET}
  expiration: 600000


logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.project.smartmeetingroom: DEBUG
